# Generated by Django 5.0.14 on 2025-11-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(default="KongLeague Aram chaos", max_length=200),
        ),
    ]
