# Generated by Django 5.0.14 on 2025-11-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_alter_tournament_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="team",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="team_logos/"),
        ),
    ]
